services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  backend:
    build: ./backend
    ports:
      - "8050:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - task-db:/var/lib/postgresql/data

volumes:
  task-db: