name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Docker
        run: docker --version

      - name: Build backend image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/task-tracker-backend:latest \
            -t ghcr.io/${{ github.repository_owner }}/task-tracker-backend:${{ github.sha }} \
            ./backend

      - name: Test backend
        run: |
          docker run --rm \
            ghcr.io/${{ github.repository_owner }}/task-tracker-backend:${{ github.sha }} \
            pytest

      - name: Build frontend image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/task-tracker-frontend:latest \
            -t ghcr.io/${{ github.repository_owner }}/task-tracker-frontend:${{ github.sha }} \
            ./frontend

      - name: Push backend image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/task-tracker-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/task-tracker-backend:${{ github.sha }}

      - name: Push frontend image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/task-tracker-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/task-tracker-frontend:${{ github.sha }}